services:
  backend:
    build:
      context: .
      target: api
    ports:
      - 3457:3457
    shm_size: 64mb
    depends_on: ["db"]
  migration:
    build:
      context: .
      target: migration
    shm_size: 64mb
    depends_on: ["db"]
    environment:
      DSN: postgres://postgres:avi123@db:5432/crawler?sslmode=disable
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: avi123
      POSTGRES_DB: crawler
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "m@m.com"
      PGADMIN_DEFAULT_PASSWORD: "1234"
    ports:
      - "16543:80"
    depends_on:
      - db
